do
$do$
begin
	if not exists (select from pg_catalog.pg_roles where rolname = 'app_btalert') then
		create user app_btalert with encrypted password 'BR:.>LuT`Lbs%6t@99w!4+Ch' 
			nosuperuser inherit nocreatedb nocreaterole noreplication valid until 'infinity';
	 	grant connect on database postgres to app_btalert;
		grant usage on schema public to app_btalert;
		grant select, insert, update, delete on all tables in schema public to app_btalert;
		grant usage, select on all sequences in schema public to app_btalert;
   end if;
end
$do$;

create sequence if not exists hibernate_sequence;

create table if not exists "user" (
    use_cod bigint not null generated by default as identity,
    use_name varchar not null,
    use_email varchar not null,
    use_phone varchar not null,
	use_password varchar not null,
    use_is_admin boolean not null default false,
    constraint user_use_cod_pkey primary key (use_cod),
    constraint user_use_email_ukey unique (use_email)
);
