FROM prom/alertmanager

COPY prometheus/alertmanager/alertmanager.yml /home/alertmanager.yml
RUN export SLACK_URL=$(echo "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzN0M5QjNVSjIvQjAzRVJFUzFIU0wvTDloUmx0enRsNlg5dmc5RDVNNjRhSTNaCg==" | base64 -d) && \
    sed -i -e "s|{{SLACK_URL}}|${SLACK_URL}|" /home/alertmanager.yml