FROM openjdk:11
WORKDIR /usr/src/app
COPY src src
COPY pom.xml pom.xml
COPY mvnw mvnw
COPY setup-env.sh setup-env.sh
COPY .mvn .mvn

RUN bash setup-env.sh docker --skipDDL
RUN bash mvnw clean package -DskipTests && cp target/server-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]